"use strict";

const isIPadOS=/\biPad\b/i.test(navigator.userAgent)||(navigator.maxTouchPoints>1&&/\bMac(?:intosh|Intel)\b/i.test(`${navigator.userAgent} ${navigator.platform}`));
document.documentElement.classList.toggle("ipad-window-ui",isIPadOS);

const DATA_FILES = Array.from({length:9},(_,i)=>`data/season${i+1}.json`);
const SERIES = [{id:"friends",name:"Friends",available:true},{id:"tbbt",name:"The Big Bang Theory",available:false}];
const LEGACY = {phraseBookmarks:"friendsBookmarks_phrase",dialogueBookmarks:"friendsBookmarks_dialogue",weak:"friendsWeakStats"};
const STORE = {state:"sitcomEnglish_v2_state",continue:"sitcomEnglish_v2_continue",activity:"sitcomEnglish_v2_activity",quiz:"sitcomEnglish_v2_quizInProgress",history:"sitcomEnglish_v2_quizHistory",dailyTarget:"sitcomEnglish_v2_dailyTarget",learned:"sitcomEnglish_learnedPhrases",sound:"sitcomEnglish_soundEnabled",jingleDate:"sitcomEnglish_lastJingleDate"};
const TODAY_TARGET = 10;

let PHRASES=[],DIALOGUES=[],SEASONS=[];
let route={name:"home",params:{}},historyStack=[],lastListContext=null,searchState={query:"",scrollTop:0},reviewPhraseSnapshot=null,searchReturnFocus=null,showPhraseTranslations=false,showDialogueTranslations=false,pendingSeasonComplete=null;
const DETAIL_SWIPE_MIN_X=64,DETAIL_SWIPE_AXIS_RATIO=1.4;
const DETAIL_SWIPE_ANIMATION_MS=180,DETAIL_SWIPE_ANIMATION_PX=30,DETAIL_SWIPE_EASING="cubic-bezier(.22,1,.36,1)";
let detailSwipeStart=null,detailSwipeAnimating=false;
let audioContext=null,activeSoundNodes=[],activeSoundRun=0;
let dialoguePlaybackActive=false,dialoguePlaybackRun=0,dialoguePlaybackPauseTimer=null,dialogueVoiceChangeHandler=null;
let filters={phrase:{season:"ALL",episode:"ALL",scope:"all",priority:"all",type:"all",usage:"all",bookmarked:false,weak:false},dialogue:{season:"ALL",episode:"ALL",category:"all",bookmarked:false},bookmarksTab:"phrase",quizSeason:"ALL",quizScope:"random"};
const app=document.getElementById("app"),backButton=document.getElementById("backButton"),searchButton=document.getElementById("searchButton"),desktopContextBar=document.getElementById("desktopContextBar"),desktopBackButton=document.getElementById("desktopBackButton");

const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const readJSON=(key,fallback)=>{try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}};
const writeJSON=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const seasonNum=value=>Number(String(value||"").match(/\d+/)?.[0])||0;
const seasonCode=n=>`S${String(Number(n)).padStart(2,"0")}`;
const episodeNumber=value=>Number(String(value||"").match(/E(\d+)/)?.[1])||0;
const localDate=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const normalize=value=>String(value||"").toLowerCase().replace(/[’]/g,"'").normalize("NFKC").replace(/\s+/g," ").trim();
function soundEnabled(){return localStorage.getItem(STORE.sound)!=="false"}
function updateSoundSettingControls(){const enabled=soundEnabled();document.querySelectorAll("[data-sound-setting]").forEach(control=>{control.setAttribute("aria-checked",String(enabled));control.querySelector(".sound-switch")?.classList.toggle("on",enabled);const state=control.querySelector(".sound-setting-state");if(state)state.textContent=enabled?"ON":"OFF"})}
function setSoundEnabled(enabled){localStorage.setItem(STORE.sound,String(enabled));if(!enabled)stopActiveSounds();updateSoundSettingControls();if(enabled)armStartupJingle()}
function soundSettingMarkup(className=""){const enabled=soundEnabled();return `<button class="sound-setting ${className}" type="button" role="switch" aria-checked="${enabled}" data-sound-setting onclick="setSoundEnabled(!soundEnabled())"><span class="sound-setting-copy"><strong>Sound</strong><small class="sound-setting-state">${enabled?'ON':'OFF'}</small></span><span class="sound-switch ${enabled?'on':''}" aria-hidden="true"><i></i></span></button>`}
function getAudioContext(){if(!audioContext){const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return null;audioContext=new AudioContextClass()}return audioContext}
function stopActiveSounds(){activeSoundRun++;activeSoundNodes.forEach(node=>{try{node.stop()}catch{}});activeSoundNodes=[]}
function playSound(notes){if(!soundEnabled())return false;const context=getAudioContext();if(!context)return false;if(context.state==="suspended")context.resume();stopActiveSounds();const run=activeSoundRun,start=context.currentTime+.015,master=context.createGain();master.gain.setValueAtTime(.0001,start);master.gain.exponentialRampToValueAtTime(.18,start+.018);master.gain.exponentialRampToValueAtTime(.0001,start+Math.max(...notes.map(note=>note.at+note.duration))+.1);master.connect(context.destination);for(const note of notes){const oscillator=context.createOscillator(),gain=context.createGain(),noteStart=start+note.at;oscillator.type=note.type||"sine";oscillator.frequency.setValueAtTime(note.frequency,noteStart);gain.gain.setValueAtTime(.0001,noteStart);gain.gain.exponentialRampToValueAtTime(note.gain||.28,noteStart+.014);gain.gain.exponentialRampToValueAtTime(.0001,noteStart+note.duration);oscillator.connect(gain);gain.connect(master);oscillator.start(noteStart);oscillator.stop(noteStart+note.duration+.02);activeSoundNodes.push(oscillator)}setTimeout(()=>{if(activeSoundRun===run)activeSoundNodes=[]},1200);return true}
function playQuizSound(correct){playSound(correct?[{frequency:659.25,at:0,duration:.18,type:"triangle",gain:.3},{frequency:987.77,at:.15,duration:.3,type:"sine",gain:.34}]:[{frequency:246.94,at:0,duration:.18,type:"triangle",gain:.25},{frequency:196,at:.15,duration:.28,type:"triangle",gain:.22}])}
function playLearnedSound(){playSound([{frequency:523.25,at:0,duration:.16,type:"sine",gain:.26},{frequency:783.99,at:.12,duration:.2,type:"triangle",gain:.3},{frequency:1174.66,at:.26,duration:.34,type:"sine",gain:.32}])}
function playSeasonCompleteSound(){playSound([{frequency:659.25,at:0,duration:.16,type:"triangle",gain:.26},{frequency:880,at:.13,duration:.2,type:"sine",gain:.3},{frequency:1318.51,at:.28,duration:.34,type:"sine",gain:.34}])}
function playStartupJingle(){const today=localDate();if(localStorage.getItem(STORE.jingleDate)===today||!soundEnabled())return;if(playSound([{frequency:523.25,at:0,duration:.2,type:"triangle",gain:.27},{frequency:659.25,at:.16,duration:.2,type:"triangle",gain:.29},{frequency:783.99,at:.32,duration:.22,type:"triangle",gain:.31},{frequency:1046.5,at:.5,duration:.42,type:"sine",gain:.35}]))localStorage.setItem(STORE.jingleDate,today)}
function armStartupJingle(){if(localStorage.getItem(STORE.jingleDate)===localDate()||!soundEnabled())return;const attempt=()=>{playStartupJingle();if(localStorage.getItem(STORE.jingleDate)===localDate()){document.removeEventListener("pointerdown",attempt,true);document.removeEventListener("keydown",attempt,true)}};document.addEventListener("pointerdown",attempt,true);document.addEventListener("keydown",attempt,true)}
function typingAnswerMatches(answer,phrase){const actual=normalize(answer),expected=normalize(phrase);if(actual===expected)return true;if(!expected.endsWith("~"))return false;return actual===expected.slice(0,-1).trimEnd()}
const PHRASE_SCOPES=new Set(["all","important","weak","unlearned","saved"]);
function phraseScopeFrom(value={}){if(PHRASE_SCOPES.has(value.scope))return value.scope;if(value.weak)return"weak";if(value.bookmarked)return"saved";if(String(value.priority)==="3")return"important";return"all"}
function withPhraseScope(value,scope=phraseScopeFrom(value)){const safe=PHRASE_SCOPES.has(scope)?scope:"all";return{...value,scope:safe,priority:safe==="important"?"3":"all",bookmarked:safe==="saved",weak:safe==="weak"}}

async function loadData(){
  const datasets=await Promise.all(DATA_FILES.map(async path=>{const response=await fetch(path);if(!response.ok)throw new Error(`${path}: ${response.status}`);return response.json()}));
  PHRASES=datasets.flatMap(x=>x.phrases||[]);DIALOGUES=datasets.flatMap(x=>x.dialogues||[]);SEASONS=datasets.map(x=>Number(x.season)).filter(Number.isFinite).sort((a,b)=>a-b);
  const saved=readJSON(STORE.state,{});if(saved.currentSeries==="friends"){const raw=saved.filters?.phrase||{},phrase={...filters.phrase,...raw,weak:false};let scope=Object.prototype.hasOwnProperty.call(raw,"scope")?raw.scope:phraseScopeFrom(raw);if(scope==="weak")scope="all";filters={...filters,...saved.filters,phrase:withPhraseScope(phrase,scope),dialogue:{...filters.dialogue,...saved.filters?.dialogue}};if(filters.quizScope==="unlearned")filters.quizScope="learned"}
}

function saveAppState(){const source=reviewPhraseSnapshot?reviewPhraseSnapshot:filters.phrase,scope=phraseScopeFrom(source)==="weak"?"all":phraseScopeFrom(source),phrase=withPhraseScope({...source,weak:false},scope);writeJSON(STORE.state,{version:2,currentSeries:"friends",filters:{...filters,phrase}});}
function navigate(name,params={},options={}){if(!options.replace)historyStack.push({name:route.name,params:{...route.params},scrollY:window.scrollY});route={name,params};render();}
function goBack(){const returnToSearch=Boolean(route.params?.fromSearch),previous=historyStack.pop();if(previous){route={name:previous.name,params:previous.params};render();requestAnimationFrame(()=>window.scrollTo({top:previous.scrollY||0,behavior:"instant"}));if(returnToSearch)requestAnimationFrame(()=>openSearch(true))}else navigate("home",{}, {replace:true});}
function goHome(){historyStack=[];route={name:"home",params:{}};render();}
function navTo(mode){if(mode==="home")return goHome();if(mode==="phrases"){filters.phrase=reviewPhraseSnapshot?withPhraseScope(reviewPhraseSnapshot):withPhraseScope(filters.phrase,phraseScopeFrom(filters.phrase)==="weak"?"all":phraseScopeFrom(filters.phrase));reviewPhraseSnapshot=null}const map={phrases:"phrases",dialogues:"dialogues",quiz:"quiz",bookmarks:"bookmarks",progress:"progress"};historyStack=[];route={name:map[mode],params:{}};render();}

function activeNav(){if(["phraseDetail","episodes"].includes(route.name))return"phrases";if(route.name==="dialogueDetail")return"dialogues";if(route.name==="quizPlay"||route.name==="quizResult")return"quiz";return route.name;}
function lineIcon(name,className=""){
  const paths={
    home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/>',
    phrases:'<path d="M5 5h14M5 10h14M5 15h10M5 20h8"/>',
    dialogues:'<path d="M4 5.5h11a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H9l-4 3v-3H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2Z"/><path d="M17 9.5h3a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-1v2l-3-2h-4a2 2 0 0 1-2-2v-2"/>',
    quiz:'<circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 3.3 2.37c-.72.29-1 .76-1 1.63v.3"/><path d="M12 17.3h.01"/>',
    bookmark:'<path d="M6 3.5h12a1 1 0 0 1 1 1v16l-7-4-7 4v-16a1 1 0 0 1 1-1Z"/>',
    menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',
    search:'<circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/>',
    settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.08A1.7 1.7 0 0 0 8.97 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.52-1.03H3v-4h.08A1.7 1.7 0 0 0 4.6 8.94a1.7 1.7 0 0 0-.34-1.88L4.2 7l2.83-2.83.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 10 3.05V3h4v.05a1.7 1.7 0 0 0 1.03 1.52 1.7 1.7 0 0 0 1.88-.34l.06-.06L19.8 7l-.06.06a1.7 1.7 0 0 0-.34 1.88A1.7 1.7 0 0 0 20.92 10H21v4h-.08A1.7 1.7 0 0 0 19.4 15Z"/>',
    help:'<circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 3.3 2.37c-.72.29-1 .76-1 1.63v.3"/><path d="M12 17.3h.01"/>',
    info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',
    progress:'<path d="M4 19V9M10 19V5M16 19v-7M22 19V3"/><path d="M3 19h20"/>',
    circleCheck:'<circle cx="12" cy="12" r="9"/><path d="m8.2 12.2 2.5 2.5 5.2-5.4"/>'
  };
  return `<svg class="line-icon ${className}" viewBox="0 0 24 24" aria-hidden="true" focusable="false">${paths[name]||""}</svg>`;
}
function renderNav(){
  const items=[['home','home','Home'],['dialogues','dialogues','Dialogues'],['quiz','quiz','Quiz'],['phrases','phrases','Phrases'],['bookmarks','bookmark','Bookmarks']];
  const navButton=([id,icon,label])=>`<button class="nav-button ${activeNav()===id?'active':''}" onclick="navTo('${id}')" aria-current="${activeNav()===id?'page':'false'}"><span class="nav-icon">${lineIcon(icon)}</span><span>${label}</span></button>`;
  const mobileHtml=items.map(navButton).join("");
  const sidebarHtml=[...items,['progress','progress','Progress']].map(navButton).join("");
  document.getElementById("bottomNav").innerHTML=mobileHtml;
  document.getElementById("sidebar").innerHTML=`<div class="sidebar-brand">Sitcom<span>English in Action</span></div><div class="sidebar-primary">${sidebarHtml}<button class="nav-button" type="button" onclick="openSearch()"><span class="nav-icon">${lineIcon("search")}</span><span>Search</span></button></div><div class="sidebar-secondary"><button class="nav-button" type="button" onclick="openHelp()"><span class="nav-icon">${lineIcon("help")}</span><span>Help</span></button>${soundSettingMarkup("sidebar-sound-setting")}<button class="nav-button" type="button" onclick="openAbout()"><span class="nav-icon">${lineIcon("info")}</span><span>About</span></button></div>`;
  const onHome=route.name==="home"&&!historyStack.length;
  backButton.disabled=false;backButton.classList.toggle("home-menu-button",onHome);backButton.setAttribute("aria-label",onHome?"Menu":"Back");backButton.innerHTML=onHome?lineIcon("menu"):"←";
  desktopContextBar.hidden=onHome;desktopBackButton.disabled=onHome;
}

function render(){
  stopDialoguePlayback(false);closeSearch();renderNav();saveAppState();
  const views={home:renderHome,series:renderSeriesHome,progress:renderProgress,episodes:renderEpisodes,phrases:()=>renderPhrasePage(false),bookmarks:renderBookmarks,phraseDetail:renderPhraseDetail,dialogues:renderDialogueList,dialogueDetail:renderDialogueDetail,quiz:renderQuizHome,quizPlay:renderQuizPlay,quizResult:renderQuizResult};
  (views[route.name]||renderHome)();app.classList.toggle("home-view",route.name==="home");app.focus({preventScroll:true});window.scrollTo({top:0,behavior:"instant"});
}

function bookmarks(type){const key=type==="phrase"?LEGACY.phraseBookmarks:LEGACY.dialogueBookmarks;const value=readJSON(key,[]);return Array.isArray(value)?value:[];}
function bookmarked(type,id){return bookmarks(type).includes(id)}
function updateBookmarkButton(button,on){if(!button)return;button.classList.toggle("on",on);button.setAttribute("aria-pressed",String(on));button.setAttribute("aria-label",on?"Remove bookmark":"Bookmark");}
function updateBookmarkCounts(){
  const total=bookmarks("phrase").length+bookmarks("dialogue").length;
  const subtitle=app.querySelector(".list-page-count, .page-header .page-subtitle");if(subtitle)subtitle.textContent=`${total} items`;
  const content=document.getElementById("bookmarkContent"),cards=content?.querySelectorAll(".phrase-card, .dialogue-card")||[];
  const result=content?.querySelector(".result-count");if(result)result.textContent=`${cards.length} results`;
  const list=content?.querySelector(".content-list");if(list&&!cards.length)list.innerHTML=`<div class="empty">No bookmarked ${filters.bookmarksTab==='phrase'?'phrases':'dialogues'}.</div>`;
}
function toggleBookmark(type,id,event){
  event?.stopPropagation();const button=event?.currentTarget;const key=type==="phrase"?LEGACY.phraseBookmarks:LEGACY.dialogueBookmarks;const old=bookmarks(type),wasOn=old.includes(id),next=wasOn?old.filter(x=>x!==id):[...old,id];writeJSON(key,next);
  if(route.name==="bookmarks"&&wasOn){const y=window.scrollY;button?.closest(".phrase-card, .dialogue-card")?.remove();updateBookmarkCounts();requestAnimationFrame(()=>window.scrollTo({top:Math.min(y,Math.max(0,document.documentElement.scrollHeight-window.innerHeight)),behavior:"instant"}));return;}
  updateBookmarkButton(button,!wasOn);
}
function bookmarkButton(type,id){const on=bookmarked(type,id);return `<button class="bookmark-button ${on?'on':''}" onclick="toggleBookmark('${type}','${id}',event)" aria-label="${on?'Remove bookmark':'Bookmark'}" aria-pressed="${on}">${lineIcon("bookmark","bookmark-icon")}</button>`;}

function learnedState(){const value=readJSON(STORE.learned,{});if(!value||typeof value!=="object"||Array.isArray(value))return{friends:[]};return{...value,friends:Array.isArray(value.friends)?value.friends:[]}}
function learnedPhraseIds(){return learnedState().friends}
function isLearned(id){return learnedPhraseIds().includes(id)}
function getLearnedCount(phrases=PHRASES){const ids=new Set(learnedPhraseIds());return phrases.reduce((count,phrase)=>count+(ids.has(phrase.id)?1:0),0)}
function getCompletionPercent(learned,total){return total?Math.round((learned/total)*1000)/10:0}
function phrasesInRange(season="ALL",episode="ALL"){return PHRASES.filter(p=>(season==="ALL"||seasonNum(p.episode)===Number(season))&&(episode==="ALL"||episodeNumber(p.episode)===Number(episode)))}
function progressFor(phrases=PHRASES){const total=phrases.length,learned=getLearnedCount(phrases);return{learned,total,remaining:Math.max(0,total-learned),percent:getCompletionPercent(learned,total)}}
function learnedButton(id){const on=isLearned(id);return `<button class="learned-button ${on?'on':''}" type="button" onclick="toggleLearned('${id}',event)" aria-pressed="${on}" aria-label="${on?'覚えた状態。未習得に戻す':'未習得。覚えた状態にする'}">${lineIcon("circleCheck","learned-icon")}<span>覚えた</span></button>`}
function updateLearnedButton(button,on){if(!button)return;button.classList.toggle("on",on);button.setAttribute("aria-pressed",String(on));button.setAttribute("aria-label",on?"覚えた状態。未習得に戻す":"未習得。覚えた状態にする")}
function toggleLearned(id,event){event?.stopPropagation();const state=learnedState(),ids=new Set(state.friends),wasOn=ids.has(id);if(wasOn)ids.delete(id);else ids.add(id);state.friends=[...ids];writeJSON(STORE.learned,state);updateLearnedButton(event?.currentTarget,!wasOn);if(!wasOn){playLearnedSound();const phrase=PHRASES.find(item=>item.id===id),season=seasonNum(phrase?.episode),seasonProgress=progressFor(phrasesInRange(season));if(seasonProgress.total>0&&seasonProgress.learned===seasonProgress.total)pendingSeasonComplete=season}}
function learnedBadge(id){return isLearned(id)?`<span class="learned-badge">${lineIcon("circleCheck","learned-icon")}<span>覚えた</span></span>`:""}

function getWeakStats(){const value=readJSON(LEGACY.weak,{});return value&&typeof value==="object"&&!Array.isArray(value)?value:{}}
function setWeakStats(value){writeJSON(LEGACY.weak,value)}
function isWeak(id){const item=getWeakStats()[id];return Boolean(item&&!item.graduated)}
function markMiss(id){const all=getWeakStats(),wasActive=Boolean(all[id]&&!all[id].graduated);all[id]={...(all[id]||{}),miss:(all[id]?.miss||0)+1,streak:0,graduated:false};setWeakStats(all);return !wasActive;}
function markWeakCorrect(id){const all=getWeakStats();if(!all[id]||all[id].graduated)return false;all[id].streak=(all[id].streak||0)+1;const graduated=all[id].streak>=2;if(graduated)all[id].graduated=true;setWeakStats(all);return graduated;}
function weakCount(){return Object.values(getWeakStats()).filter(x=>x&&!x.graduated).length}

function dailyTarget(){const value=Number(localStorage.getItem(STORE.dailyTarget));return Number.isInteger(value)&&value>0&&value<=999?value:TODAY_TARGET}

function recordStudy(kind,id){
  const activity=readJSON(STORE.activity,{dates:{},target:TODAY_TARGET});activity.dates=activity.dates||{};const today=localDate();const items=new Set(activity.dates[today]?.items||[]);items.add(`${kind}:${id}`);activity.dates[today]={items:[...items]};activity.target=activity.target||TODAY_TARGET;writeJSON(STORE.activity,activity);
}
function activityStats(){
  const activity=readJSON(STORE.activity,{dates:{},target:TODAY_TARGET}),today=localDate(),todayCount=activity.dates?.[today]?.items?.length||0;let streak=0,cursor=new Date();
  if(!activity.dates?.[today]?.items?.length)cursor.setDate(cursor.getDate()-1);
  while(activity.dates?.[localDate(cursor)]?.items?.length){streak++;cursor.setDate(cursor.getDate()-1)}
  return{today:todayCount,target:dailyTarget(),streak};
}
function setContinue(value){writeJSON(STORE.continue,{series:"friends",timestamp:Date.now(),...value})}
function getContinue(){const value=readJSON(STORE.continue,null);if(!value)return null;if(value.kind==="phrase"&&!PHRASES.some(x=>x.id===value.id))return null;if(value.kind==="dialogue"&&!DIALOGUES.some(x=>x.id===value.id))return null;return value;}
function continueLearning(){const value=getContinue();if(!value)return navigate("series");if(value.kind==="phrase")navigate("phraseDetail",{id:value.id,from:"continue"});else navigate("dialogueDetail",{id:value.id,from:"continue"});}

function closeModal(){document.getElementById("modalRoot").innerHTML="";document.body.classList.remove("modal-open")}
function closeCreatorEasterEgg(){const overlay=document.getElementById("creatorEasterEgg");if(!overlay)return;overlay.remove();const aboutModal=document.querySelector(".about-modal");aboutModal?.removeAttribute("inert");aboutModal?.removeAttribute("aria-hidden");document.querySelector(".about-creator")?.focus({preventScroll:true})}
function openCreatorEasterEgg(){if(document.getElementById("creatorEasterEgg"))return;const aboutModal=document.querySelector(".about-modal"),overlay=document.createElement("div");overlay.id="creatorEasterEgg";overlay.className="modal-backdrop creator-easter-egg-backdrop";overlay.onclick=event=>{if(event.target===overlay)closeCreatorEasterEgg()};overlay.innerHTML=`<section class="creator-easter-egg-modal" role="dialog" aria-modal="true" aria-label="Aki.n and Mochi's study room"><button class="icon-button modal-close creator-easter-egg-close" type="button" onclick="closeCreatorEasterEgg()" aria-label="Close">×</button><img src="assets/aki-n-mochi.jpg" alt="勉強部屋のうさぎとMochi"></section>`;document.getElementById("modalRoot").appendChild(overlay);document.body.classList.add("modal-open");overlay.querySelector(".creator-easter-egg-close")?.focus({preventScroll:true});aboutModal?.setAttribute("inert","");aboutModal?.setAttribute("aria-hidden","true")}
function openHomeMenu(){
  document.getElementById("modalRoot").innerHTML=`<div class="drawer-backdrop" onclick="closeModal()"><aside class="home-drawer" role="dialog" aria-modal="true" aria-labelledby="menuTitle" onclick="event.stopPropagation()"><div class="drawer-heading"><h2 id="menuTitle">Menu</h2><button class="icon-button modal-close" type="button" onclick="closeModal()" aria-label="Close">×</button></div><nav class="drawer-nav" aria-label="Menu"><div class="drawer-menu-scroll">${soundSettingMarkup("drawer-sound-setting")}<div class="drawer-divider"></div><button class="drawer-row" type="button" onclick="closeModal();navTo('progress')"><span class="drawer-icon">${lineIcon("progress")}</span><span>Progress</span></button><button class="drawer-row" type="button" onclick="openHelp()"><span class="drawer-icon">${lineIcon("help")}</span><span>Help</span></button></div><button class="drawer-row drawer-about" type="button" onclick="openAbout()"><span class="drawer-icon">${lineIcon("info")}</span><span>About</span></button></nav></aside></div>`;
}
function targetButton(value,current){return `<button class="chip ${current===value?'selected':''}" type="button" aria-pressed="${current===value}" onclick="setDailyTarget(${value})">${value}</button>`}
function openTarget(showCustom=false,error=""){
  const current=dailyTarget(),custom=showCustom||![5,10,20].includes(current);
  document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="targetTitle"><div class="modal-heading"><h2 id="targetTitle">Daily Target</h2><button class="icon-button modal-close" type="button" onclick="closeModal()" aria-label="Close">×</button></div><div class="target-options">${targetButton(5,current)}${targetButton(10,current)}${targetButton(20,current)}<button class="chip ${custom?'selected':''}" type="button" aria-pressed="${custom}" onclick="openTarget(true)">Custom</button></div>${custom?`<div class="custom-target"><label for="customTarget">Phrases per day</label><input id="customTarget" class="select" type="number" inputmode="numeric" min="1" max="999" step="1" value="${current}"><button class="primary-button" type="button" onclick="saveCustomTarget()">Save</button></div>`:""}${error?`<p class="setting-error" role="alert">${esc(error)}</p>`:""}</div></div>`;
}
function setDailyTarget(value){if(!Number.isInteger(value)||value<1||value>999)return;localStorage.setItem(STORE.dailyTarget,String(value));closeModal();if(route.name==="home")renderHome()}
function saveCustomTarget(){const value=Number(document.getElementById("customTarget")?.value);if(!Number.isInteger(value)||value<1||value>999)return openTarget(true,"Enter a whole number from 1 to 999.");setDailyTarget(value)}
function openStreak(){const days=activityStats().streak,message=days===0?"Start your streak today!":days===1?"Nice start!":`${days}-day streak! Keep it going.`;document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop" onclick="closeModal()"><div class="modal streak-modal" role="dialog" aria-modal="true" aria-labelledby="streakTitle" onclick="event.stopPropagation()"><div class="modal-heading"><h2 id="streakTitle">Streak</h2><button class="icon-button modal-close" type="button" onclick="closeModal()" aria-label="Close">×</button></div><div class="streak-emoji">🔥</div><strong class="streak-days">${days} ${days===1?'day':'days'}</strong><p class="muted">${esc(message)}</p></div></div>`}
function openWeakReview(){reviewPhraseSnapshot={...filters.phrase};filters.phrase=withPhraseScope({...filters.phrase,season:"ALL",episode:"ALL"},"weak");historyStack=[];route={name:"phrases",params:{reviewMode:true}};render()}
function openAbout(){
  document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop about-backdrop" onclick="closeModal()"><section class="modal about-modal" role="dialog" aria-modal="true" aria-labelledby="aboutTitle" onclick="event.stopPropagation()"><div class="modal-heading"><h2 id="aboutTitle">About</h2><button class="icon-button modal-close" type="button" onclick="closeModal()" aria-label="Close">×</button></div><div class="about-content"><div class="about-brand">Sitcom English in Action</div><p class="muted">Version 4.3</p><div class="about-series"><strong>Friends</strong><span>S1–S9</span><span>${PHRASES.length} phrases</span><span>${DIALOGUES.length} dialogues</span><span class="about-secondary">Season 10 Coming Soon</span></div><div class="about-series"><strong>The Big Bang Theory</strong><span>Coming Soon</span></div><section class="about-concept"><h3>Concept</h3><p>海外ドラマで出会った英語を、「分かる」で終わらせず「使える」まで。</p><p>DialogueやQuizを入口に、気になった表現を深掘りして、聞く・話す・覚えるを行き来しながら身につけるための学習アプリです。</p><p class="about-concept-english">Built for sitcom lovers who want to actually use the English they hear.</p><button class="about-creator" type="button" onclick="openCreatorEasterEgg()">Created by aki.n &amp; Mochi 🐼</button></section></div></section></div>`;
  document.body.classList.add("modal-open");
}
function helpFaq(question,answer){return `<details class="help-faq"><summary>${question}</summary><div>${answer}</div></details>`}
function openHelp(){
  const faqs=[
    ["Progressの数字は何？",`<p><strong>253 / 1063 learned</strong>なら、253は「覚えた」にしたPhrase数、1063は収録Phrase総数です。Season別も、そのSeasonで「覚えた」にしたPhrase数 / そのSeasonの総Phrase数を表します。</p>`],
    ["Soundって何の音？",`<p>Quizの正解 / 不正解、「覚えた」を押した時、起動時などの効果音です。英文の音声読み上げとは別の機能です。</p>`],
    ["「覚えた」とBookmarkは何が違う？",`<p>「覚えた」は学習進捗を記録する機能です。Bookmarkは、あとで見返したいPhrase / Dialogueを保存する機能です。両者は独立しています。</p>`],
    ["「習得済み」って何？",`<p>「覚えた」を押したPhraseのことです。PhrasesやQuizで、習得済みPhraseを対象に含めたり絞り込んだりできます。</p>`],
    ["「重要」って何？",`<p>★★★が付いている、優先的に覚えたいPhraseです。重要な表現から先に学習したい時の絞り込みに使えます。</p>`],
    ["「苦手」って何？",`<p>クイズで間違えたフレーズが、自動で「苦手」に分類されます。「苦手」で絞り込むと、間違えたPhraseをまとめて復習できます。</p>`],
    ["「使用感」って何？",`<p>Phraseを使う場面や学習の優先順位を考えるための目安です。</p><p><strong>日常的：</strong>今でも日常会話で自然に使いやすい表現<br><strong>知っておきたい：</strong>頻繁に使わなくても、ドラマや会話で分かると便利な表現<br><strong>やや古め：</strong>意味は通じるものの、今の会話では少し古く感じられたり、使う場面が限られる表現</p><p>「覚える / 覚えない」を決める絶対的な分類ではありません。</p>`],
    ["🔊とPlay Dialogueの違いは？",`<p><strong>🔊</strong>は、その例文またはセリフだけを音声で読み上げます。<strong>Play Dialogue</strong>は、Dialogue全体を順番に音声再生します。</p>`],
    ["Hide A / Hide Bって何？",`<p>選んだ側の英語を隠して、自分で言う練習ができる機能です。日本語訳ONなら日本語をヒントに英語を思い出す練習、OFFなら完全暗唱ができます。Play Dialogueと組み合わせると、アプリが表示されている側を読み上げ、ユーザーが隠した側を担当するロールプレイができます。</p>`],
    ["学習データはどこに保存される？",`<p>学習データと設定は、この端末・ブラウザのlocalStorageに保存されます。アカウント同期型ではないため、端末やブラウザ間で自動同期されません。ブラウザデータを削除すると、履歴が失われる可能性があります。</p>`]
  ];
  document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop help-backdrop" onclick="closeModal()"><section class="modal help-modal" role="dialog" aria-modal="true" aria-labelledby="helpTitle" onclick="event.stopPropagation()"><div class="modal-heading"><h2 id="helpTitle">Help</h2><button class="icon-button modal-close" type="button" onclick="closeModal()" aria-label="Close">×</button></div><div class="help-content"><section class="help-intro"><div class="eyebrow">Getting Started</div><h3>どこから始めてもOK！</h3><p>全部のPhraseを最初から順番に覚える必要はありません。会話・Quiz・Phrase一覧から、好きな入口を選んで始めましょう。</p></section><div class="help-paths"><section class="help-path"><h3>会話から覚えたい → Dialogues</h3><ul><li>会話の流れを読み、日本語訳をON / OFF</li><li>Hide A / Hide Bで片方を隠して発話練習</li><li>慣れたら日本語訳OFFで暗唱</li><li>Play Dialogueで会話全体を音声再生し、アプリを相手役にロールプレイ</li></ul></section><section class="help-path"><h3>ゲーム感覚で試したい → Quiz</h3><ul><li>まずQuizを解いてみる</li><li>間違えたPhraseはResultからDetailへ移動</li><li>分からなかった表現だけ詳しく復習</li></ul></section><section class="help-path"><h3>じっくり覚えたい → Phrases</h3><ul><li>意味・場面・Examples・日本語訳を確認</li><li>🔊で例文の発音を確認</li><li>重要・苦手・未習得などで絞り込み</li><li>習得したら「覚えた」にする</li></ul></section></div><section class="help-faqs"><h3>FAQ</h3>${faqs.map(([question,answer])=>helpFaq(question,answer)).join("")}</section></div></section></div>`;
  document.body.classList.add("modal-open");
}

function pageHeader(eyebrow,title,subtitle=""){return `<header class="page-header"><div class="eyebrow">${esc(eyebrow)}</div><h1 class="page-title">${esc(title)}</h1>${subtitle?`<p class="page-subtitle">${esc(subtitle)}</p>`:""}</header>`}
function listPageHeader(title,countLabel){return `<header class="page-header list-page-header"><h1 class="list-page-title">FRIENDS · ${esc(title)}</h1><p class="list-page-count">${esc(countLabel)}</p></header>`}
function chips(values,selected,handler,prefix="",allLabel="ALL"){return `<div class="chips">${values.map(value=>{const active=String(value)===String(selected),label=value==="ALL"?allLabel:prefix==="E"?`E${String(value).padStart(2,"0")}`:`${prefix}${value}`;return `<button class="chip ${active?'selected':''}" aria-pressed="${active}" onclick="${handler}('${value}')">${esc(label)}</button>`}).join("")}</div>`}
function quizStatsMarkup(){const h=readJSON(STORE.history,[]),last=h.at(-1),best=h.length?[...h].sort((a,b)=>(b.score/b.total)-(a.score/a.total)||b.score-a.score)[0]:null,today=[...h].reverse().find(x=>x.completedDate===localDate()||(!x.completedDate&&localDate(new Date(x.completedAt))===localDate()));return `<div class="stats-row"><div class="stat-box"><span>Last score</span><strong>${last?`${last.score}/${last.total}`:'—'}</strong></div><div class="stat-box"><span>Best score</span><strong>${best?`${best.score}/${best.total}`:'—'}</strong></div><div class="stat-box"><span>Today</span><strong>${today?`${today.score}/${today.total}`:'0/10'}</strong></div></div>`}

function renderHome(){
  const a=activityStats(),overall=progressFor(),cont=getContinue(),p=cont?.kind==="phrase"?PHRASES.find(x=>x.id===cont.id):null,d=cont?.kind==="dialogue"?DIALOGUES.find(x=>x.id===cont.id):null;
  const studiedToday=a.today>0,streakStatus=studiedToday?"Today ✓":"Not yet?",streakDaysLabel=`${a.streak} ${a.streak===1?'day':'days'}`;
  const continueTitle=p?p.phrase:d?d.title:"Friends · Choose where to start";const continueMeta=p?`Friends · ${p.episode} · Phrases`:d?`Friends · ${d.season} · Dialogues`:"Your learning position will appear here.";
  app.innerHTML=`<div class="dashboard">
    <section class="brand-visual"><h1 class="sr-only">Sitcom English in Action</h1><img src="assets/app-brand.webp" alt="Sitcom English in Action — 海外ドラマで楽しく英語を学ぼう" width="1600" height="640"></section>
    <section class="card"><div class="section-head"><h2 class="section-title">Today</h2></div><div class="today-grid"><button class="today-stat streak-stat ${studiedToday?'studied-today':'not-studied-today'}" type="button" onclick="openStreak()" aria-label="Streak: ${streakDaysLabel}. ${streakStatus}"><span class="today-icon streak-fire" aria-hidden="true">🔥</span><span class="today-label">Streak</span><strong class="today-value">${streakDaysLabel}</strong><span class="today-status">${streakStatus}</span></button><button class="today-stat" type="button" onclick="openTarget()"><span class="today-icon">🎯</span><span class="today-label">Target</span><strong class="today-value">${a.today} / ${a.target}</strong><span class="today-status">So far</span></button><button class="today-stat" type="button" onclick="navigate('progress')"><span class="today-icon">📈</span><span class="today-label">Progress</span><strong class="today-value">${overall.learned} / ${overall.total}</strong><span class="today-status">Overall</span></button></div></section>
    <section class="card continue-card"><div><div class="continue-kicker">Continue Learning</div><h2 class="continue-title">${esc(continueTitle)}</h2><div class="continue-meta">${esc(continueMeta)}${cont?`<br>Last studied: ${localDate(new Date(cont.timestamp))===localDate()?'Today':localDate(new Date(cont.timestamp))}`:""}</div></div><button class="primary-button" onclick="continueLearning()">Continue →</button></section>
    <section class="card series-section"><div class="section-head"><h2 class="section-title">Series</h2></div><div class="series-grid">${SERIES.map(s=>`<button class="series-card series-${s.id} ${s.available?'':'disabled'}" ${s.available?'onclick="navigate(\'series\')"':'disabled'}><span class="series-overlay"><span class="series-name">${esc(s.name)}</span><span class="series-state">${s.available?'S1–S9 available':'Coming Soon'}</span></span></button>`).join("")}</div></section>
    <section class="card compact-card"><div><h2 class="section-title">Daily Quiz</h2><p class="page-subtitle">10 questions. See what sticks.</p><div class="desktop-only section">${quizStatsMarkup()}</div></div><button class="primary-button" onclick="navigate('quiz')">Start →</button></section>
  </div>`;
}

function renderSeriesHome(){
  const bCount=bookmarks("phrase").length+bookmarks("dialogue").length,overall=progressFor();
  app.innerHTML=`${pageHeader("Series","Friends",`${overall.learned} / ${overall.total} learned · ${DIALOGUES.length} dialogues`)}<section class="section"><div class="section-head"><h2 class="section-title">Study by Mode</h2></div><div class="list-rows">
    <button class="list-row" onclick="navigate('phrases')"><strong>Phrases</strong><span class="row-end"><span class="row-meta">${overall.learned} / ${overall.total} learned</span>›</span></button>
    <button class="list-row" onclick="navigate('dialogues')"><strong>Dialogues</strong><span class="row-end"><span class="row-meta">${DIALOGUES.length} dialogues</span>›</span></button>
    <button class="list-row" onclick="navigate('quiz')"><strong>Quiz</strong><span class="row-end"><span class="row-meta">Daily Quiz</span>›</span></button>
    <button class="list-row" onclick="navigate('bookmarks')"><strong>Bookmarks</strong><span class="row-end"><span class="row-meta">${bCount} items</span>›</span></button>
    <button class="list-row progress-mode-row" onclick="navigate('progress')"><strong>Progress</strong><span class="row-end"><span class="row-meta">${overall.percent}% complete</span>›</span></button></div></section>
    <section class="section"><div class="section-head"><h2 class="section-title">Browse by Season</h2></div>${chips(["ALL",...SEASONS],"ALL","browseSeason",'S')}</section>
    <section class="card section"><div class="section-head"><h2 class="section-title">How to use</h2></div><div class="how-list"><div class="how-item"><span class="how-icon">⌕</span><div><strong>Find what you need</strong><span>Filter by Phrases or choose a Season.</span></div></div><div class="how-item"><span class="how-icon">→</span><div><strong>Study by Episode</strong><span>Pick an episode and start learning.</span></div></div></div></section>`;
}
function progressBarMarkup(progress,label){return `<div class="progress-track" role="progressbar" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress.percent}"><span style="width:${progress.percent}%"></span></div>`}
function renderProgress(){
  const overall=progressFor(),seasonProgress=SEASONS.map(season=>{const progress=progressFor(phrasesInRange(season));return{season,...progress,complete:progress.total>0&&progress.learned===progress.total}}),celebratedSeason=seasonProgress.some(item=>item.season===pendingSeasonComplete&&item.complete)?pendingSeasonComplete:null;pendingSeasonComplete=null;
  app.innerHTML=`${pageHeader("Friends","Progress",`${overall.learned} / ${overall.total} learned`)}<section class="card progress-overall"><div class="progress-overall-head"><div><div class="eyebrow">Overall Progress</div><h2>Friends</h2></div><div class="progress-total"><strong>${overall.learned} / ${overall.total}</strong><span>${overall.percent}% complete</span></div></div>${progressBarMarkup(overall,"Friends overall progress")}<div class="progress-summary"><div><span>Learned</span><strong>${overall.learned}</strong></div><div><span>Remaining</span><strong>${overall.remaining}</strong></div><div><span>Completion</span><strong>${overall.percent}%</strong></div></div></section><section class="section"><div class="section-head"><h2 class="section-title">By Season</h2></div><div class="season-progress-list">${seasonProgress.map(item=>`<button class="season-progress-card ${celebratedSeason===item.season?'season-complete-celebration':''}" type="button" onclick="openProgressSeason(${item.season})"><span class="season-progress-head"><strong>Season ${item.season}</strong><span>${item.learned} / ${item.total} learned</span></span>${progressBarMarkup(item,`Season ${item.season} progress`)}<span class="season-progress-foot"><span class="season-progress-status"><span>${item.percent}% complete</span>${item.complete?'<span class="season-complete-badge">🏆 COMPLETE</span>':""}</span><span class="season-progress-chevron" aria-hidden="true">›</span></span></button>`).join("")}${SEASONS.includes(10)?"":'<div class="coming-season"><strong>S10</strong><span>Coming Soon</span></div>'}</div></section><section class="progress-reset-section"><button class="progress-reset-button" type="button" onclick="confirmResetLearned()">学習進捗をリセット</button></section>`;
  if(celebratedSeason)playSeasonCompleteSound();
}
function confirmResetLearned(){document.getElementById("modalRoot").innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="resetLearnedTitle" aria-describedby="resetLearnedDescription"><h2 id="resetLearnedTitle">学習進捗をリセットしますか？</h2><p id="resetLearnedDescription" class="muted">「覚えた」状態をすべて解除します。<br>この操作は元に戻せません。</p><div class="button-row"><button class="secondary-button" type="button" onclick="closeModal()">キャンセル</button><button class="danger-button" type="button" onclick="resetLearnedProgress()">リセット</button></div></div></div>`}
function resetLearnedProgress(){const state=learnedState();state.friends=[];pendingSeasonComplete=null;writeJSON(STORE.learned,state);closeModal();renderProgress()}
function openProgressSeason(season){reviewPhraseSnapshot=null;filters.phrase=withPhraseScope({...filters.phrase,season:String(Number(season)),episode:"ALL",type:"all",usage:"all"},"all");navigate("phrases")}
function browseSeason(value){reviewPhraseSnapshot=null;const scope=phraseScopeFrom(filters.phrase)==="weak"?"all":phraseScopeFrom(filters.phrase);filters.phrase=withPhraseScope({...filters.phrase,season:value==="ALL"?"ALL":String(Number(value)),episode:"ALL"},scope);navigate("phrases")}
function episodeValues(season){return [...new Set(PHRASES.filter(p=>seasonNum(p.episode)===Number(season)).map(p=>episodeNumber(p.episode)))].sort((a,b)=>a-b)}
function renderEpisodes(){const season=route.params.season,eps=episodeValues(season);app.innerHTML=`${pageHeader("Friends",`Season ${season}`,"Choose an episode to preview its phrases.")}<div class="list-rows episode-list">${eps.map(ep=>{const count=PHRASES.filter(p=>seasonNum(p.episode)===season&&episodeNumber(p.episode)===ep).length;return `<button class="list-row episode-row" onclick="openEpisode(${season},${ep})"><strong>Episode ${String(ep).padStart(2,'0')}</strong><span class="row-end"><span class="row-meta">${count} phrases</span><span class="episode-chevron">›</span></span></button>`}).join("")}</div>`}
function openEpisode(season,episode){filters.phrase={...filters.phrase,season:String(season),episode:String(episode)};navigate("phrases")}

function setPhraseScope(scope){filters.phrase=withPhraseScope(filters.phrase,scope);saveAppState();route.name==="bookmarks"?renderBookmarks():renderPhrasePage(false)}
function setPhraseFilter(key,value){if(key==="priority")return setPhraseScope(String(value)==="3"?"important":"all");if(key==="weak")return setPhraseScope(value?"weak":"all");if(key==="bookmarked")return setPhraseScope(value?"saved":"all");filters.phrase[key]=value;if(key==="season")filters.phrase.episode="ALL";saveAppState();route.name==="bookmarks"?renderBookmarks():renderPhrasePage(false)}
function phraseScopeChips(f,bookmarkedOnly){const options=[['all','全て'],['important','重要'],['weak','苦手'],['unlearned','未習得'],...(!bookmarkedOnly?[["saved","保存"]]:[])];return `<div class="chips scope-chips">${options.map(([value,label])=>`<button class="chip ${f.scope===value?'selected':''}" aria-pressed="${f.scope===value}" onclick="setPhraseScope('${value}')">${label}</button>`).join("")}</div>`}
function phraseFilterPanel(bookmarkedOnly=false){const f=filters.phrase,eps=f.season==="ALL"?[]:episodeValues(f.season),types=[...new Set(PHRASES.map(p=>p.type))].sort(),usageValues=[...new Set(PHRASES.map(p=>p.usage))],usageOrder=["日常的","知っておきたい","やや古め"],usages=[...usageOrder.filter(x=>usageValues.includes(x)),...usageValues.filter(x=>!usageOrder.includes(x)).sort()];return `<aside class="filter-panel phrase-filter-panel card"><div class="filter-group"><div class="filter-label">シーズン</div>${chips(["ALL",...SEASONS],f.season,"setPhraseFilter.bind(null,'season')",'S','全て').replaceAll("setPhraseFilter.bind(null,'season')('","setPhraseFilter('season','")}</div>${f.season!=="ALL"?`<div class="filter-group"><div class="filter-label">エピソード</div>${chips(["ALL",...eps],f.episode,"setPhraseFilter.bind(null,'episode')",'E','全て').replaceAll("setPhraseFilter.bind(null,'episode')('","setPhraseFilter('episode','")}</div>`:""}<div class="filter-group scope-filter-group"><div class="filter-label">絞り込み</div>${phraseScopeChips(f,bookmarkedOnly)}</div><div class="phrase-select-grid"><div class="filter-group"><label class="filter-label" for="typeFilter">種類</label><select id="typeFilter" class="select" onchange="setPhraseFilter('type',this.value)"><option value="all">すべて</option>${types.map(x=>`<option ${f.type===x?'selected':''}>${esc(x)}</option>`).join("")}</select></div><div class="filter-group"><label class="filter-label" for="usageFilter">使用感</label><select id="usageFilter" class="select" onchange="setPhraseFilter('usage',this.value)"><option value="all">すべて</option>${usages.map(x=>`<option ${f.usage===x?'selected':''}>${esc(x)}</option>`).join("")}</select></div></div></aside>`}
function filteredPhrases(bookmarkedOnly=false){const f=filters.phrase,scope=phraseScopeFrom(f);return PHRASES.filter(p=>(!(bookmarkedOnly||scope==="saved")||bookmarked("phrase",p.id))&&(scope!=="weak"||isWeak(p.id))&&(scope!=="unlearned"||!isLearned(p.id))&&(f.season==="ALL"||seasonNum(p.episode)===Number(f.season))&&(f.episode==="ALL"||episodeNumber(p.episode)===Number(f.episode))&&(scope!=="important"||Number(p.priority)===3)&&(f.type==="all"||p.type===f.type)&&(f.usage==="all"||p.usage===f.usage));}
function phraseCard(p,opener="openPhrase"){return `<article class="phrase-card" role="button" tabindex="0" data-card-opener="${opener}" data-card-id="${p.id}">${bookmarkButton("phrase",p.id)}<div class="phrase-name">${esc(p.phrase)}</div><div class="meaning">${esc(p.meaning)}</div><div class="meta-line"><span class="tag priority">${esc(p.priorityText)}</span><span class="tag">${esc(p.type)}</span><span class="tag">${esc(p.usage)}</span><span class="tag">${esc(p.episode)}</span>${learnedBadge(p.id)}</div></article>`}
function renderPhrasePage(bookmarkedOnly=false){const list=filteredPhrases(bookmarkedOnly),range=phrasesInRange(filters.phrase.season,filters.phrase.episode),progress=progressFor(range);lastListContext={type:bookmarkedOnly?"bookmarks":"phrases",ids:list.map(x=>x.id)};app.innerHTML=`${listPageHeader(bookmarkedOnly?"Bookmarks":"Phrases",bookmarkedOnly?`${list.length} items`:`${progress.learned} / ${progress.total} learned`)}<div class="filter-layout">${phraseFilterPanel(bookmarkedOnly)}<section><div class="result-count">${list.length} results</div><div class="content-list phrase-grid">${list.map(p=>phraseCard(p)).join("")||'<div class="empty">No matching phrases.</div>'}</div></section></div>`}
function phraseNavigationIds(id=route.params.id){const ids=Array.isArray(route.params.ids)?route.params.ids:PHRASES.map(x=>x.id);return ids.includes(id)?ids:PHRASES.map(x=>x.id)}
function openPhrase(id){setContinue({kind:"phrase",id});recordStudy("phrase",id);const fromPhraseList=route.name==="phrases"||(route.name==="bookmarks"&&filters.bookmarksTab==="phrase"),ids=fromPhraseList&&lastListContext?.ids?.includes(id)?[...lastListContext.ids]:PHRASES.map(x=>x.id);navigate("phraseDetail",{id,ids})}
function phraseMove(delta){const ids=phraseNavigationIds(),pos=ids.indexOf(route.params.id),id=ids[pos+delta];if(id){route.params={...route.params,id};setContinue({kind:"phrase",id});recordStudy("phrase",id);render()}}
function speechAvailable(){return"speechSynthesis" in window&&typeof SpeechSynthesisUtterance!=="undefined"}
function updateDialoguePlaybackButton(){const button=document.querySelector(".dialogue-play-button");if(!button)return;button.classList.toggle("playing",dialoguePlaybackActive);button.setAttribute("aria-pressed",String(dialoguePlaybackActive));button.setAttribute("aria-label",dialoguePlaybackActive?"Stop dialogue playback":"Play dialogue");button.textContent=dialoguePlaybackActive?"■ Stop":"▶ Play Dialogue"}
function clearDialogueVoiceWait(){if(dialogueVoiceChangeHandler&&"speechSynthesis" in window)window.speechSynthesis.removeEventListener("voiceschanged",dialogueVoiceChangeHandler);dialogueVoiceChangeHandler=null}
function stopDialoguePlayback(updateButton=true){dialoguePlaybackRun++;dialoguePlaybackActive=false;if(dialoguePlaybackPauseTimer!==null)clearTimeout(dialoguePlaybackPauseTimer);dialoguePlaybackPauseTimer=null;clearDialogueVoiceWait();if("speechSynthesis" in window)window.speechSynthesis.cancel();if(updateButton)updateDialoguePlaybackButton()}
function speakExample(text){if(!text||!speechAvailable())return;stopDialoguePlayback();const utterance=new SpeechSynthesisUtterance(text);utterance.lang="en-US";window.speechSynthesis.speak(utterance)}
function togglePhraseTranslations(){showPhraseTranslations=!showPhraseTranslations;renderPhraseDetail()}
function exampleMarkup(text,translation,label){if(!text)return"";return `<div class="example-row"><div class="example"><div class="example-copy"><span class="example-text">${esc(text)}</span>${showPhraseTranslations&&translation?`<span class="example-translation" lang="ja">${esc(translation)}</span>`:""}</div><button class="speaker-button" type="button" data-text="${esc(text)}" onclick="speakExample(this.dataset.text)" aria-label="Read ${label} aloud">🔊</button></div></div>`}
function openRelatedDialogue(id){const ids=DIALOGUES.filter(d=>(d.phraseLinks||[]).includes(route.params.id)).map(d=>d.id);setContinue({kind:"dialogue",id});recordStudy("dialogue",id);navigate("dialogueDetail",{id,ids,practice:"normal",revealed:[]})}
function renderPhraseDetail(){const p=PHRASES.find(x=>x.id===route.params.id);if(!p)return navigate("phrases");const ids=phraseNavigationIds(p.id),pos=ids.indexOf(p.id),related=DIALOGUES.filter(d=>(d.phraseLinks||[]).includes(p.id)),translations=p.exampleTranslations||[];app.innerHTML=`<main class="detail-page phrase-detail-page"><div class="dialogue-pager"><button class="text-button" ${pos<=0?'disabled':''} onclick="phraseMove(-1)">← Previous</button><span></span><button class="text-button" ${pos<0||pos>=ids.length-1?'disabled':''} onclick="phraseMove(1)">Next →</button></div><article class="card detail-card"><div class="detail-actions">${learnedButton(p.id)}${bookmarkButton("phrase",p.id)}</div><div class="eyebrow">${esc(p.episode)}</div><h1 class="detail-title">${esc(p.phrase)}</h1><div class="meaning detail-meaning">${esc(p.meaning)}</div><div class="meta-line"><span class="tag priority">${esc(p.priorityText)}</span><span class="tag">${esc(p.type)}</span><span class="tag">${esc(p.usage)}</span><span class="tag">${esc(p.episode)}</span></div><p class="detail-copy muted">${esc(p.scene)}</p><section class="detail-section"><div class="examples-section-head"><h2 class="section-title">Examples</h2><button class="translation-toggle ${showPhraseTranslations?'selected':''}" type="button" aria-pressed="${showPhraseTranslations}" onclick="togglePhraseTranslations()"><span>日本語訳</span><strong>${showPhraseTranslations?'表示':'非表示'}</strong></button></div>${exampleMarkup(p.example1,translations[0],"example 1")}${exampleMarkup(p.example2,translations[1],"example 2")}</section><section class="detail-section"><h2 class="section-title">Used in Dialogues</h2><div class="related-dialogues">${related.map(d=>`<button class="related-dialogue" type="button" onclick="openRelatedDialogue('${d.id}')"><span>${esc(d.title)}</span><span aria-hidden="true">›</span></button>`).join("")||'<div class="empty compact-empty">No related dialogues</div>'}</div></section></article></main>`}

function dialogueEpisodes(d){const linked=new Set(d.phraseLinks||[]);return [...new Set(PHRASES.filter(p=>linked.has(p.id)).map(p=>p.episode))].sort()}
function compactEpisodeList(episodes,fallback=""){if(!episodes.length)return fallback;const groups=[];for(const episode of episodes){const season=seasonNum(episode),number=episodeNumber(episode),last=groups.at(-1);if(last?.season===season)last.episodes.push(number);else groups.push({season,episodes:[number]})}return groups.map(group=>`${seasonCode(group.season)} · ${group.episodes.map(number=>`E${String(number).padStart(2,"0")}`).join(" / ")}`).join(" · ")}
function dialogueCategory(d){const match=String(d.title||"").match(/^([^①②③④⑤⑥⑦⑧⑨⑩（(]+)/);return match?.[1]?.trim()||""}
function dialogueText(d){return [d.title,...d.lines.flatMap(x=>[x[1],x[2]])].join(" ")}
function setDialogueFilter(key,value){filters.dialogue[key]=value;if(key==="season")filters.dialogue.episode="ALL";saveAppState();route.name==="bookmarks"?renderBookmarks():renderDialogueList(false)}
function dialogueFilterPanel(bookmarkedOnly=false){const f=filters.dialogue,eps=f.season==="ALL"?[]:episodeValues(f.season),categories=[...new Set(DIALOGUES.map(dialogueCategory).filter(Boolean))].sort();return `<aside class="filter-panel card"><div class="filter-group"><div class="filter-label">Season</div>${chips(["ALL",...SEASONS],f.season,"setDialogueFilter.bind(null,'season')",'S').replaceAll("setDialogueFilter.bind(null,'season')('","setDialogueFilter('season','")}</div>${f.season!=="ALL"?`<div class="filter-group"><div class="filter-label">Episode</div>${chips(["ALL",...eps],f.episode,"setDialogueFilter.bind(null,'episode')",'E').replaceAll("setDialogueFilter.bind(null,'episode')('","setDialogueFilter('episode','")}</div>`:""}<div class="filter-group"><label class="filter-label" for="categoryFilter">Category</label><select id="categoryFilter" class="select" onchange="setDialogueFilter('category',this.value)"><option value="all">All categories</option>${categories.map(x=>`<option ${f.category===x?'selected':''}>${esc(x)}</option>`).join("")}</select></div>${!bookmarkedOnly?`<button class="secondary-button icon-label ${f.bookmarked?'selected-filter':''}" aria-pressed="${f.bookmarked}" onclick="setDialogueFilter('bookmarked',${!f.bookmarked})">${lineIcon("bookmark")}<span>Bookmarked</span></button>`:""}</aside>`}
function filteredDialogues(bookmarkedOnly=false){const f=filters.dialogue;return DIALOGUES.filter(d=>(!(bookmarkedOnly||f.bookmarked)||bookmarked("dialogue",d.id))&&(f.season==="ALL"||seasonNum(d.season)===Number(f.season))&&(f.episode==="ALL"||dialogueEpisodes(d).some(ep=>episodeNumber(ep)===Number(f.episode)))&&(f.category==="all"||dialogueCategory(d)===f.category));}
function dialogueCard(d,opener="openDialogue"){const eps=dialogueEpisodes(d),category=dialogueCategory(d),linked=d.phraseLinks?.length||0;return `<article class="dialogue-card" role="button" tabindex="0" data-card-opener="${opener}" data-card-id="${d.id}"><div class="dialogue-card-body">${bookmarkButton("dialogue",d.id)}<div class="dialogue-title">${esc(d.title)}</div><div class="dialogue-counts">${d.lines.length} lines · ${linked} phrases</div><div class="dialogue-meta">${category?`<span class="tag">${esc(category)}</span>`:""}<span class="episode-text">${esc(compactEpisodeList(eps,d.season))}</span></div></div></article>`}
function renderDialogueList(bookmarkedOnly=false){const list=filteredDialogues(bookmarkedOnly);lastListContext={type:"dialogues",ids:list.map(x=>x.id)};app.innerHTML=`${listPageHeader(bookmarkedOnly?"Bookmarks":"Dialogues",bookmarkedOnly?`${list.length} items`:`${list.length===DIALOGUES.length?DIALOGUES.length+' dialogues':list.length+' results'}`)}<div class="filter-layout">${dialogueFilterPanel(bookmarkedOnly)}<section><div class="result-count">${list.length} results</div><div class="content-list dialogue-list">${list.map(d=>dialogueCard(d)).join("")||'<div class="empty">No matching dialogues.</div>'}</div></section></div>`}
function openDialogue(id){setContinue({kind:"dialogue",id});recordStudy("dialogue",id);const ids=lastListContext?.ids?.includes(id)?lastListContext.ids:filteredDialogues().map(x=>x.id);navigate("dialogueDetail",{id,ids,practice:"normal",revealed:[]})}
function setPractice(mode){route.params.practice=mode;route.params.revealed=[];renderDialogueDetail()}
function toggleDialogueTranslations(){showDialogueTranslations=!showDialogueTranslations;renderDialogueDetail()}
function dialogueLineMarkup(line,index,linked){return `<div class="dialogue-line"><div class="dialogue-line-copy"><div class="dialogue-line-text">${highlightDialogueLine(line[1],linked)}</div>${showDialogueTranslations?`<div class="translation">${esc(line[2])}</div>`:""}</div><button class="speaker-button" type="button" data-text="${esc(line[1])}" onclick="speakExample(this.dataset.text)" aria-label="Read dialogue line ${index+1} aloud">🔊</button></div>`}
function revealLine(index){const d=DIALOGUES.find(x=>x.id===route.params.id),line=d?.lines?.[index],target=document.querySelector(`.hidden-line[data-line-index="${index}"]`);if(!line||!target)return;route.params.revealed=route.params.revealed||[];if(!route.params.revealed.includes(index))route.params.revealed.push(index);const linked=(d.phraseLinks||[]).map(id=>PHRASES.find(p=>p.id===id)).filter(Boolean);target.outerHTML=dialogueLineMarkup(line,index,linked)}
function dialogueMove(delta){const ids=route.params.ids||DIALOGUES.map(x=>x.id),pos=ids.indexOf(route.params.id),id=ids[pos+delta];if(id){route.params={...route.params,id,practice:"normal",revealed:[]};setContinue({kind:"dialogue",id});recordStudy("dialogue",id);render()}}
function detailSwipeRoute(){return route.name==="dialogueDetail"||route.name==="phraseDetail"}
function detailSwipeBlocked(){const selection=window.getSelection?.();return Boolean(document.getElementById("searchOverlay")||document.getElementById("modalRoot")?.childElementCount||selection&&(!selection.isCollapsed||selection.toString().trim()))}
function detailSwipeInteractiveTarget(target){return target instanceof Element&&Boolean(target.closest("button,input,select,textarea,a,label,summary,[role='button'],[contenteditable='true']"))}
function detailSwipeDirection(deltaX,deltaY){const absX=Math.abs(deltaX),absY=Math.abs(deltaY);return absX>=DETAIL_SWIPE_MIN_X&&absX>=absY*DETAIL_SWIPE_AXIS_RATIO?(deltaX<0?1:-1):0}
function detailSwipeCanMove(direction){const buttons=app.querySelectorAll(".detail-page .dialogue-pager>button");return Boolean(buttons.length===2&&!(direction<0?buttons[0]:buttons[1]).disabled)}
async function animateDetailSwipe(direction){if(detailSwipeAnimating||!detailSwipeRoute()||!detailSwipeCanMove(direction))return;const routeName=route.name,itemId=route.params.id,move=routeName==="phraseDetail"?phraseMove:dialogueMove,page=app.querySelector(".detail-page"),reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;if(!page||reduced||typeof page.animate!=="function"){move(direction);return}detailSwipeAnimating=true;let moved=false;page.classList.add("detail-swipe-transition");try{await page.animate([{transform:"translateX(0)",opacity:1},{transform:`translateX(${-direction*DETAIL_SWIPE_ANIMATION_PX}px)`,opacity:0}],{duration:DETAIL_SWIPE_ANIMATION_MS,easing:DETAIL_SWIPE_EASING,fill:"forwards"}).finished;if(route.name!==routeName||route.params.id!==itemId)return;move(direction);moved=route.name===routeName&&route.params.id!==itemId;if(!moved)return;const incoming=app.querySelector(".detail-page");if(!incoming)return;incoming.classList.add("detail-swipe-transition");await incoming.animate([{transform:`translateX(${direction*DETAIL_SWIPE_ANIMATION_PX}px)`,opacity:0},{transform:"translateX(0)",opacity:1}],{duration:DETAIL_SWIPE_ANIMATION_MS,easing:DETAIL_SWIPE_EASING,fill:"both"}).finished}catch{if(!moved&&route.name===routeName&&route.params.id===itemId)move(direction)}finally{app.querySelector(".detail-page")?.classList.remove("detail-swipe-transition");detailSwipeAnimating=false}}
function startDetailSwipe(event){detailSwipeStart=null;if(detailSwipeAnimating||!detailSwipeRoute()||event.touches.length!==1||detailSwipeBlocked()||detailSwipeInteractiveTarget(event.target))return;const touch=event.touches[0];detailSwipeStart={x:touch.clientX,y:touch.clientY,identifier:touch.identifier,routeName:route.name,itemId:route.params.id}}
function finishDetailSwipe(event){const start=detailSwipeStart;detailSwipeStart=null;if(!start||route.name!==start.routeName||route.params.id!==start.itemId||detailSwipeBlocked())return;const touch=Array.from(event.changedTouches).find(item=>item.identifier===start.identifier);if(!touch)return;const direction=detailSwipeDirection(touch.clientX-start.x,touch.clientY-start.y);if(direction)animateDetailSwipe(direction)}
function cancelDetailSwipe(){detailSwipeStart=null}
function dialoguePracticeDelay(text){const words=String(text||"").trim().split(/\s+/).filter(Boolean).length;return Math.min(8000,Math.max(1800,700+words*380))}
function englishDialogueVoices(){return window.speechSynthesis.getVoices().filter(voice=>/^en(?:[-_]|$)/i.test(voice.lang||""))}
function playDialogue(){const d=DIALOGUES.find(x=>x.id===route.params.id);if(!d?.lines?.length||!speechAvailable())return;stopDialoguePlayback(false);dialoguePlaybackActive=true;const run=dialoguePlaybackRun,mode=route.params.practice||"normal",userRole=mode==="hideA"?"A":mode==="hideB"?"B":null;updateDialoguePlaybackButton();const start=voices=>{if(run!==dialoguePlaybackRun||!dialoguePlaybackActive||document.hidden||!voices.length)return false;clearDialogueVoiceWait();if(dialoguePlaybackPauseTimer!==null)clearTimeout(dialoguePlaybackPauseTimer);dialoguePlaybackPauseTimer=null;const voiceA=voices[0],voiceB=voices[1]||voiceA;let index=0;const finish=()=>{if(run!==dialoguePlaybackRun)return;dialoguePlaybackActive=false;dialoguePlaybackPauseTimer=null;updateDialoguePlaybackButton()};const playNext=()=>{if(run!==dialoguePlaybackRun||!dialoguePlaybackActive)return;dialoguePlaybackPauseTimer=null;const line=d.lines[index++];if(!line)return finish();if(line[0]===userRole){dialoguePlaybackPauseTimer=setTimeout(playNext,dialoguePracticeDelay(line[1]));return}const utterance=new SpeechSynthesisUtterance(line[1]);utterance.lang="en-US";utterance.voice=line[0]==="B"?voiceB:voiceA;utterance.onend=()=>{if(run!==dialoguePlaybackRun||!dialoguePlaybackActive)return;if(index>=d.lines.length)return finish();dialoguePlaybackPauseTimer=setTimeout(playNext,240)};utterance.onerror=event=>{if(run!==dialoguePlaybackRun||event.error==="canceled"||event.error==="interrupted")return;finish()};try{window.speechSynthesis.speak(utterance)}catch{finish()}};playNext();return true};if(start(englishDialogueVoices()))return;dialogueVoiceChangeHandler=()=>start(englishDialogueVoices());window.speechSynthesis.addEventListener("voiceschanged",dialogueVoiceChangeHandler);dialoguePlaybackPauseTimer=setTimeout(()=>{if(run!==dialoguePlaybackRun||!dialoguePlaybackActive)return;clearDialogueVoiceWait();dialoguePlaybackPauseTimer=null;dialoguePlaybackActive=false;updateDialoguePlaybackButton()},3000)}
function toggleDialoguePlayback(){dialoguePlaybackActive?stopDialoguePlayback():playDialogue()}
function highlightDialogueLine(text,linked){let output=esc(text);linked.sort((a,b)=>b.phrase.length-a.phrase.length).forEach(p=>{const raw=String(p.phrase).replace(/\([^)]*\)|someone|somebody|something|~/gi," ").trim();if(raw.length<4)return;const safe=raw.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");output=output.replace(new RegExp(`(${safe})`,`ig`),'<span class="highlight-phrase">$1</span>')});return output}
function renderDialogueDetail(){stopDialoguePlayback(false);const d=DIALOGUES.find(x=>x.id===route.params.id);if(!d)return navigate("dialogues");const ids=route.params.ids||DIALOGUES.map(x=>x.id),pos=ids.indexOf(d.id),mode=route.params.practice||"normal",revealed=route.params.revealed||[],linked=(d.phraseLinks||[]).map(id=>PHRASES.find(p=>p.id===id)).filter(Boolean),eps=dialogueEpisodes(d);const conversation=d.lines.map((line,i)=>{const hide=mode===`hide${line[0]}`&&!revealed.includes(i);return `<div class="bubble-row ${line[0].toLowerCase()}"><div class="bubble"><div class="speaker-label">${line[0]}</div>${hide?`<div class="hidden-line" data-line-index="${i}" role="button" tabindex="0" onclick="revealLine(${i})" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();revealLine(${i})}">${showDialogueTranslations?`<div class="translation hidden-line-translation">${esc(line[2])}</div>`:""}<div>Tap to reveal</div></div>`:dialogueLineMarkup(line,i,linked)}</div></div>`}).join("");app.innerHTML=`<main class="detail-page dialogue-detail-page"><div class="dialogue-pager"><button class="text-button" ${pos<=0?'disabled':''} onclick="dialogueMove(-1)">← Previous</button><span></span><button class="text-button" ${pos<0||pos>=ids.length-1?'disabled':''} onclick="dialogueMove(1)">Next →</button></div><header class="page-header detail-page-header"><div class="eyebrow">Friends · ${esc(eps.join(' · ')||d.season)}</div><h1 class="page-title">${esc(d.title)}</h1>${bookmarkButton("dialogue",d.id)}</header><div class="dialogue-layout"><section><div class="dialogue-controls"><div class="segmented"><button class="seg-button ${mode==='normal'?'selected':''}" aria-pressed="${mode==='normal'}" onclick="setPractice('normal')">Normal</button><button class="seg-button ${mode==='hideA'?'selected':''}" aria-pressed="${mode==='hideA'}" onclick="setPractice('hideA')">Hide A</button><button class="seg-button ${mode==='hideB'?'selected':''}" aria-pressed="${mode==='hideB'}" onclick="setPractice('hideB')">Hide B</button></div><button class="translation-toggle ${showDialogueTranslations?'selected':''}" type="button" aria-pressed="${showDialogueTranslations}" onclick="toggleDialogueTranslations()"><span>日本語訳</span><strong>${showDialogueTranslations?'表示':'非表示'}</strong></button><button class="secondary-button dialogue-play-button" type="button" aria-pressed="false" aria-label="Play dialogue" onclick="toggleDialoguePlayback()">▶ Play Dialogue</button></div><div class="conversation">${conversation}</div></section><aside class="dialogue-side card"><h2 class="section-title">このダイアログの学習フレーズ</h2><div class="learning-list">${linked.map((p,i)=>`<div class="learning-item" role="button" tabindex="0" onclick="openPhrase('${p.id}')" onkeydown="if(event.key==='Enter'){openPhrase('${p.id}')}" ><strong>${i+1}. ${esc(p.phrase)}</strong><span>${esc(p.meaning)}</span></div>`).join("")||'<div class="empty">Linked phrases are not registered.</div>'}</div></aside></div></main>`}

function renderBookmarks(){const tab=filters.bookmarksTab,list=tab==="phrase"?filteredPhrases(true):filteredDialogues(true);app.innerHTML=`${listPageHeader("Bookmarks",`${list.length} items`)}<div class="segmented section"><button class="seg-button ${tab==='phrase'?'selected':''}" aria-pressed="${tab==='phrase'}" onclick="filters.bookmarksTab='phrase';render()">Phrases</button><button class="seg-button ${tab==='dialogue'?'selected':''}" aria-pressed="${tab==='dialogue'}" onclick="filters.bookmarksTab='dialogue';render()">Dialogues</button></div><div id="bookmarkContent"></div>`;if(tab==="phrase"){lastListContext={type:"bookmarks",ids:list.map(x=>x.id)};document.getElementById("bookmarkContent").innerHTML=`<div class="filter-layout">${phraseFilterPanel(true)}<section><div class="result-count">${list.length} results</div><div class="content-list phrase-grid">${list.map(p=>phraseCard(p)).join("")||'<div class="empty">No bookmarked phrases.</div>'}</div></section></div>`}else{lastListContext={type:"dialogues",ids:list.map(x=>x.id)};document.getElementById("bookmarkContent").innerHTML=`<div class="filter-layout">${dialogueFilterPanel(true)}<section><div class="result-count">${list.length} results</div><div class="content-list dialogue-list">${list.map(d=>dialogueCard(d)).join("")||'<div class="empty">No bookmarked dialogues.</div>'}</div></section></div>`}}

function setQuizOption(key,value){filters[key]=value;saveAppState();renderQuizHome()}
function quizPool(season=filters.quizSeason,scope=filters.quizScope){return PHRASES.filter(p=>(season==="ALL"||seasonNum(p.episode)===Number(season))&&(scope!=="star3"||Number(p.priority)===3)&&(scope!=="bookmarked"||bookmarked("phrase",p.id))&&(scope!=="weak"||isWeak(p.id))&&(scope!=="learned"||isLearned(p.id)))}
function renderQuizHome(){const session=readJSON(STORE.quiz,null),pool=quizPool();app.innerHTML=`${pageHeader("Friends · Quiz","Daily Quiz","10 questions per session")}<div class="filter-layout"><section class="card filter-panel"><div class="filter-group"><div class="filter-label">シーズン</div>${chips(["ALL",...SEASONS],filters.quizSeason,"setQuizOption.bind(null,'quizSeason')",'S','全て').replaceAll("setQuizOption.bind(null,'quizSeason')('","setQuizOption('quizSeason','")}</div><div class="filter-group"><div class="filter-label">絞り込み</div><div class="chips scope-chips"><button class="chip ${filters.quizScope==='random'?'selected':''}" onclick="setQuizOption('quizScope','random')">全て</button><button class="chip ${filters.quizScope==='star3'?'selected':''}" onclick="setQuizOption('quizScope','star3')">重要</button><button class="chip ${filters.quizScope==='weak'?'selected':''}" onclick="setQuizOption('quizScope','weak')">苦手</button><button class="chip ${filters.quizScope==='learned'?'selected':''}" onclick="setQuizOption('quizScope','learned')">習得済み</button><button class="chip ${filters.quizScope==='bookmarked'?'selected':''}" onclick="setQuizOption('quizScope','bookmarked')">保存</button></div></div><div class="page-subtitle">${pool.length} phrases available</div></section><section class="card"><h2 class="section-title">Your Quiz</h2>${quizStatsMarkup()}${session?`<div class="section"><strong>Quiz in progress</strong><p class="page-subtitle">${session.responses.length} / ${session.questions.length} completed</p></div><div class="button-row"><button class="primary-button" onclick="navigate('quizPlay')">Resume Quiz</button><button class="secondary-button" onclick="confirmStartOver()">Start Over</button></div>`:`${!pool.length?'<div class="empty compact-empty quiz-empty" role="status">対象のフレーズがありません。</div>':''}<button class="primary-button section" ${pool.length?'onclick="startQuiz()"':'disabled'}>Start Daily Quiz</button>`}</section></div>`}
function shuffle(values){const a=[...values];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function createQuestions(pool){const selected=shuffle(pool).slice(0,Math.min(10,pool.length)),pattern=["mc","fill","tf","mc","fill","tf","mc","fill","tf","mc"];return selected.map((p,i)=>{const type=pattern[i],others=shuffle(PHRASES.filter(x=>x.id!==p.id));if(type==="mc")return{id:p.id,type,choices:shuffle([p.id,...others.slice(0,3).map(x=>x.id)])};if(type==="tf"){const truth=Math.random()<.5;return{id:p.id,type,presentedMeaning:truth?p.meaning:others[0].meaning,trueAnswer:truth};}return{id:p.id,type};})}
function startQuiz(){const pool=quizPool();if(!pool.length){renderQuizHome();return}const session={version:2,series:"friends",season:filters.quizSeason,scope:filters.quizScope,questions:createQuestions(pool),index:0,responses:[],score:0,added:0,graduated:0,mistakes:[],startedAt:new Date().toISOString()};writeJSON(STORE.quiz,session);navigate("quizPlay")}
function confirmStartOver(){showConfirm("Start the quiz over? Your current quiz progress will be replaced.",()=>{localStorage.removeItem(STORE.quiz);startQuiz()})}
function renderQuizPlay(){const s=readJSON(STORE.quiz,null);if(!s)return navigate("quiz");const q=s.questions[s.index],p=PHRASES.find(x=>x.id===q.id),response=s.responses.find(x=>x.index===s.index);const progress=Math.round((s.responses.length/s.questions.length)*100);let question="",answers="";if(q.type==="mc"){question=`Which phrase matches this meaning?<br><span class="muted">${esc(p.meaning)}</span>`;answers=q.choices.map(id=>{const choice=PHRASES.find(x=>x.id===id),cls=response?(id===p.id?'correct':response.answer===id?'incorrect':''):'';return `<button class="answer-button ${cls}" ${response?'disabled':''} onclick="answerQuiz('${id}')">${esc(choice.phrase)}</button>`}).join("")}else if(q.type==="fill"){question=`Fill in the English phrase.<br><span class="muted">${esc(p.meaning)}</span>`;answers=response?`<input class="blank-input" value="${esc(response.answer)}" disabled><div class="example">Correct: ${esc(p.phrase)}</div>`:`<input id="fillAnswer" class="blank-input" autocomplete="off" placeholder="Type the phrase"><button class="primary-button" onclick="answerQuiz(document.getElementById('fillAnswer').value)">Check Answer</button>`}else{question=`True or False?<br><span class="phrase-name">${esc(p.phrase)}</span><br><span class="muted">${esc(q.presentedMeaning)}</span>`;answers=[true,false].map(value=>`<button class="answer-button ${response?(value===q.trueAnswer?'correct':response.answer===value?'incorrect':''):''}" ${response?'disabled':''} onclick="answerQuiz(${value})">${value?'True':'False'}</button>`).join("")}
  app.innerHTML=`${pageHeader("Friends · Daily Quiz",`Question ${s.index+1} / ${s.questions.length}`)}<div class="quiz-progress"><span style="width:${progress}%"></span></div><section class="card section"><div class="quiz-question">${question}</div><div class="answer-list">${answers}</div>${response?quizFeedback(p,response,s):""}</section>`;if(q.type==="fill"&&!response)setTimeout(()=>document.getElementById("fillAnswer")?.focus(),0)}
function answerQuiz(answer){const s=readJSON(STORE.quiz,null);if(!s||s.responses.some(x=>x.index===s.index))return;const q=s.questions[s.index],p=PHRASES.find(x=>x.id===q.id);let correct=false;if(q.type==="mc")correct=answer===p.id;else if(q.type==="fill")correct=typingAnswerMatches(answer,p.phrase);else correct=answer===q.trueAnswer;let added=false,graduated=false;if(correct){graduated=markWeakCorrect(p.id)}else{added=markMiss(p.id);s.mistakes.push(p.id)}if(correct)s.score++;if(added)s.added++;if(graduated)s.graduated++;s.responses.push({index:s.index,answer,correct,added,graduated});writeJSON(STORE.quiz,s);recordStudy("quiz",p.id);playQuizSound(correct);renderQuizPlay()}
function quizFeedback(p,response,s){return `<div class="feedback ${response.correct?'good':'bad'}"><strong>${response.correct?'Correct':'Incorrect'}</strong><div>${esc(p.phrase)} — ${esc(p.meaning)}</div>${p.example1?`<div class="search-snippet">${esc(p.example1)}</div>`:""}</div><button class="primary-button" onclick="nextQuiz()">${s.index+1>=s.questions.length?'See Results':'Next Question'}</button>`}
function nextQuiz(){const s=readJSON(STORE.quiz,null);if(!s)return;if(s.index+1>=s.questions.length)return completeQuiz(s);s.index++;writeJSON(STORE.quiz,s);renderQuizPlay()}
function completeQuiz(s){const result={score:s.score,total:s.questions.length,mistakes:[...new Set(s.mistakes)],added:s.added,graduated:s.graduated,completedAt:new Date().toISOString(),completedDate:localDate()};const history=readJSON(STORE.history,[]);history.push(result);writeJSON(STORE.history,history.slice(-100));localStorage.removeItem(STORE.quiz);route={name:"quizResult",params:{result}};render()}
function renderQuizResult(){const r=route.params.result||readJSON(STORE.history,[]).at(-1);if(!r)return navigate("quiz");const mistakes=r.mistakes.map(id=>PHRASES.find(x=>x.id===id)).filter(Boolean);app.innerHTML=`${pageHeader("Friends · Daily Quiz","Result")}<section class="card"><div class="result-score">${r.score} / ${r.total}</div><div class="stats-row"><div class="stat-box"><span>Added to Weak</span><strong>${r.added}</strong></div><div class="stat-box"><span>Graduated</span><strong>${r.graduated}</strong></div><div class="stat-box"><span>Mistakes</span><strong>${mistakes.length}</strong></div></div>${mistakes.length?`<h2 class="section-title section">今回間違えたphrase</h2><div class="mistake-list">${mistakes.map(p=>`<button class="learning-item mistake-item" type="button" onclick="openPhrase('${p.id}')" aria-label="${esc(p.phrase)}の詳細を開く"><span class="mistake-copy"><strong>${esc(p.phrase)}</strong><span>${esc(p.meaning)}</span></span><span class="mistake-chevron" aria-hidden="true">›</span></button>`).join("")}</div>`:""}<div class="button-row section"><button class="secondary-button" ${mistakes.length?'onclick="reviewMistakes()"':'disabled'}>Review mistakes</button><button class="primary-button" onclick="navTo('quiz')">Done</button></div></section>`}
function reviewMistakes(){const r=route.params.result;if(!r?.mistakes?.length)return;const pool=r.mistakes.map(id=>PHRASES.find(p=>p.id===id)).filter(Boolean);const s={version:2,series:"friends",season:"ALL",scope:"mistakes",questions:createQuestions(pool),index:0,responses:[],score:0,added:0,graduated:0,mistakes:[],startedAt:new Date().toISOString()};writeJSON(STORE.quiz,s);navigate("quizPlay")}

function searchText(q){const n=normalize(q);return{phrases:PHRASES.filter(p=>normalize([p.phrase,p.meaning,p.example1,p.example2].join(" ")).includes(n)).slice(0,40),dialogues:DIALOGUES.filter(d=>normalize(dialogueText(d)).includes(n)).slice(0,30)}}
function openSearch(restore=false){if(document.getElementById("searchOverlay"))return;searchReturnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;const overlay=document.createElement("div");overlay.id="searchOverlay";overlay.className="modal-backdrop search-backdrop";overlay.onclick=event=>{if(event.target===overlay)closeSearch()};overlay.innerHTML=`<section class="modal search-modal" role="dialog" aria-modal="true" aria-labelledby="searchTitle"><div class="modal-heading"><h2 id="searchTitle">Search</h2><button class="icon-button modal-close" type="button" onclick="closeSearch()" aria-label="Close">×</button></div><input id="universalSearch" class="search-input" placeholder="Search phrases, meanings, examples, dialogues" aria-label="Universal Search"><div id="searchResults" class="search-results"><div class="empty">Search within Friends.</div></div></section>`;overlay.addEventListener("click",event=>{if(event.target.closest(".bookmark-button"))return;const card=event.target.closest(".phrase-card,.dialogue-card");if(card&&overlay.contains(card))activateCard(card)});overlay.addEventListener("keydown",event=>{const card=event.target.closest?.(".phrase-card,.dialogue-card");if(card&&(event.key==="Enter"||event.key===" ")){event.preventDefault();activateCard(card)}});document.body.appendChild(overlay);document.body.classList.add("modal-open");const input=document.getElementById("universalSearch"),results=document.getElementById("searchResults");input.value=restore?searchState.query:"";input.addEventListener("input",()=>{searchState.query=input.value;renderSearch(input.value)});if(input.value)renderSearch(input.value);if(restore)requestAnimationFrame(()=>results.scrollTo({top:searchState.scrollTop,behavior:"instant"}));input.focus({preventScroll:true})}
function closeSearch(){const overlay=document.getElementById("searchOverlay");if(!overlay)return;overlay.remove();document.body.classList.remove("modal-open");const target=searchReturnFocus;searchReturnFocus=null;if(target?.isConnected)target.focus({preventScroll:true})}
function openSearchResult(type,id){const results=document.getElementById("searchResults");searchState={query:document.getElementById("universalSearch")?.value||searchState.query,scrollTop:results?.scrollTop||0};closeSearch();if(type==="phrase"){setContinue({kind:"phrase",id});recordStudy("phrase",id);navigate("phraseDetail",{id,fromSearch:true})}else{setContinue({kind:"dialogue",id});recordStudy("dialogue",id);navigate("dialogueDetail",{id,ids:searchText(searchState.query).dialogues.map(x=>x.id),fromSearch:true})}}
function renderSearch(query){const root=document.getElementById("searchResults");if(!root)return;searchState.query=query;if(!query.trim()){root.innerHTML='<div class="empty">Search within Friends.</div>';return}const result=searchText(query);root.innerHTML=`<section class="search-section"><h2 class="section-title">Phrases · ${result.phrases.length}</h2><div class="content-list phrase-grid">${result.phrases.map(p=>phraseCard(p,"openSearchPhraseResult")).join("")||'<div class="muted">No phrase matches.</div>'}</div></section><section class="search-section"><h2 class="section-title">Dialogues · ${result.dialogues.length}</h2><div class="content-list dialogue-list">${result.dialogues.map(d=>dialogueCard(d,"openSearchDialogueResult")).join("")||'<div class="muted">No dialogue matches.</div>'}</div></section>`}
function openSearchPhraseResult(id){openSearchResult("phrase",id)}
function openSearchDialogueResult(id){openSearchResult("dialogue",id)}
function showConfirm(message,action){const root=document.getElementById("modalRoot");root.innerHTML=`<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true"><h2>Confirm</h2><p class="muted">${esc(message)}</p><div class="button-row"><button class="secondary-button" id="cancelConfirm">Cancel</button><button class="primary-button" id="acceptConfirm">Start Over</button></div></div></div>`;document.getElementById("cancelConfirm").onclick=closeModal;document.getElementById("acceptConfirm").onclick=()=>{closeModal();action()}}

backButton.addEventListener("click",()=>route.name==="home"&&!historyStack.length?openHomeMenu():goBack());searchButton.addEventListener("click",openSearch);
desktopBackButton.addEventListener("click",goBack);
function activateCard(card){const actions={openPhrase,openDialogue,openSearchPhraseResult,openSearchDialogueResult},action=actions[card?.dataset.cardOpener];if(action)action(card.dataset.cardId)}
app.addEventListener("click",event=>{if(event.target.closest(".bookmark-button"))return;const card=event.target.closest(".phrase-card,.dialogue-card");if(card&&app.contains(card))activateCard(card)});
app.addEventListener("keydown",event=>{if(event.target.matches(".phrase-card,.dialogue-card")&&(event.key==="Enter"||event.key===" ")){event.preventDefault();activateCard(event.target)}});
app.addEventListener("touchstart",startDetailSwipe,{passive:true});
app.addEventListener("touchend",finishDetailSwipe,{passive:true});
app.addEventListener("touchcancel",cancelDetailSwipe,{passive:true});
document.addEventListener("keydown",event=>{if(event.key==="Escape"){if(document.getElementById("creatorEasterEgg"))closeCreatorEasterEgg();else{closeSearch();closeModal()}}});
document.addEventListener("visibilitychange",()=>{if(document.hidden)stopDialoguePlayback(false);else updateDialoguePlaybackButton()});
window.addEventListener("pagehide",()=>stopDialoguePlayback(false));
window.addEventListener("pageshow",updateDialoguePlaybackButton);
document.addEventListener("freeze",()=>stopDialoguePlayback(false));
document.addEventListener("DOMContentLoaded",async()=>{try{await loadData();render();armStartupJingle()}catch(error){console.error(error);app.innerHTML='<section class="card"><h1>Data could not be loaded.</h1><p class="muted">Open the app through GitHub Pages or a local web server.</p></section>'}});
